ABC_25 = [['diff_bin'],
          ['diff_bin', 'color'],
          ['diff_bin', 'color', 'day_game_num'],
          ['diff_bin', 'color', 'game_time'],
          ['diff_bin', 'color', 'game_time', 'day_game_num'],
          ['diff_bin', 'color', 'game_time', 'weekday'],
          ['diff_bin', 'color', 'game_time', 'weekday', 'day_game_num'],
          ['diff_bin', 'color', 'time_bin'],
          ['diff_bin', 'color', 'time_bin', 'day_game_num'],
          ['diff_bin', 'color', 'time_bin', 'game_time'],
          ['diff_bin', 'color', 'time_bin', 'game_time', 'day_game_num'],
          ['diff_bin', 'color', 'time_bin', 'game_time', 'weekday'],
          ['diff_bin', 'color', 'time_bin', 'game_time', 'weekday', 'day_game_num'],
          ['diff_bin', 'color', 'time_bin', 'weekday'],
          ['diff_bin', 'color', 'time_bin', 'weekday', 'day_game_num'],
          ['diff_bin', 'color', 'weekday'],
          ['diff_bin', 'color', 'weekday', 'day_game_num'],
          ['diff_bin', 'day_game_num'],
          ['diff_bin', 'game_time'],
          ['diff_bin', 'game_time', 'day_game_num'],
          ['diff_bin', 'game_time', 'weekday'],
          ['diff_bin', 'game_time', 'weekday', 'day_game_num'],
          ['diff_bin', 'time_bin'],
          ['diff_bin', 'time_bin', 'day_game_num'],
          ['diff_bin', 'time_bin', 'game_time'],
          ['diff_bin', 'time_bin', 'game_time', 'day_game_num'],
          ['diff_bin', 'time_bin', 'game_time', 'weekday'],
          ['diff_bin', 'time_bin', 'game_time', 'weekday', 'day_game_num'],
          ['diff_bin', 'time_bin', 'weekday'],
          ['diff_bin', 'time_bin', 'weekday', 'day_game_num'],
          ['diff_bin', 'weekday'],
          ['diff_bin', 'weekday', 'day_game_num']]

ABC_200 = [['diff_bin'],
          ['diff_bin', 'color'],
          ['diff_bin', 'color', 'day_game_num'],
          ['diff_bin', 'color', 'game_time'],
          ['diff_bin', 'color', 'game_time', 'day_game_num'],
          ['diff_bin', 'color', 'game_time', 'weekday'],
          ['diff_bin', 'color', 'game_time', 'weekday', 'day_game_num'],
          ['diff_bin', 'color', 'weekday'],
          ['diff_bin', 'color', 'weekday', 'day_game_num'],
          ['diff_bin', 'day_game_num'],
          ['diff_bin', 'game_time'],
          ['diff_bin', 'game_time', 'day_game_num'],
          ['diff_bin', 'game_time', 'weekday'],
          ['diff_bin', 'game_time', 'weekday', 'day_game_num'],
          ['diff_bin', 'weekday'],
          ['diff_bin', 'weekday', 'day_game_num']]

ABC_167 = [['diff_bin'],
          ['diff_bin', 'color'],
          ['diff_bin', 'color', 'day_game_num'],
          ['diff_bin', 'color', 'game_time'],
          ['diff_bin', 'color', 'game_time', 'day_game_num'],
          ['diff_bin', 'color', 'game_time', 'weekday', 'day_game_num'],
          ['diff_bin', 'color', 'time_bin'],
          ['diff_bin', 'color', 'time_bin', 'day_game_num'],
          ['diff_bin', 'color', 'time_bin', 'game_time'],
          ['diff_bin', 'color', 'time_bin', 'game_time', 'day_game_num'],
          ['diff_bin', 'color', 'time_bin', 'game_time', 'weekday'],
          ['diff_bin', 'color', 'time_bin', 'game_time', 'weekday', 'day_game_num'],
          ['diff_bin', 'color', 'time_bin', 'weekday'],
          ['diff_bin', 'color', 'time_bin', 'weekday', 'day_game_num'],
          ['diff_bin', 'color', 'weekday', 'day_game_num'],
          ['diff_bin', 'day_game_num'],
          ['diff_bin', 'game_time'],
          ['diff_bin', 'game_time', 'day_game_num'],
          ['diff_bin', 'game_time', 'weekday', 'day_game_num'],
          ['diff_bin', 'time_bin'],
          ['diff_bin', 'time_bin', 'day_game_num'],
          ['diff_bin', 'time_bin', 'game_time'],
          ['diff_bin', 'time_bin', 'game_time', 'day_game_num'],
          ['diff_bin', 'time_bin', 'game_time', 'weekday'],
          ['diff_bin', 'time_bin', 'game_time', 'weekday', 'day_game_num'],
          ['diff_bin', 'time_bin', 'weekday'],
          ['diff_bin', 'time_bin', 'weekday', 'day_game_num'],
          ['diff_bin', 'weekday', 'day_game_num']]

ABC_143 = [['color', 'game_time', 'weekday'],
          ['diff_bin', 'color', 'game_time', 'weekday'],
          ['diff_bin', 'color', 'game_time', 'weekday', 'day_game_num'],
          ['diff_bin', 'game_time', 'weekday'],
          ['diff_bin', 'game_time', 'weekday', 'day_game_num']]

ABC_125 = [['diff_bin', 'color', 'elo'],
          ['diff_bin', 'color', 'elo', 'day_game_num'],
          ['diff_bin', 'color', 'elo', 'opp_elo'],
          ['diff_bin', 'color', 'elo', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'color', 'opp_elo'],
          ['diff_bin', 'color', 'weekday', 'elo', 'opp_elo'],
          ['diff_bin', 'color', 'weekday', 'elo', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'color', 'weekday', 'opp_elo'],
          ['diff_bin', 'color', 'weekday', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'elo'],
          ['diff_bin', 'elo', 'day_game_num'],
          ['diff_bin', 'elo', 'opp_elo'],
          ['diff_bin', 'elo', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'opp_elo'],
          ['diff_bin', 'weekday', 'elo', 'opp_elo'],
          ['diff_bin', 'weekday', 'elo', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'weekday', 'opp_elo'],
          ['diff_bin', 'weekday', 'opp_elo', 'day_game_num']]

ABC_111 = [['color', 'weekday'],
          ['weekday']]

ABC_100 = [['color', 'game_time', 'weekday'],
          ['weekday'],
          ['game_time', 'weekday']]

ABC_091 = [['diff_bin'],
          ['diff_bin', 'color'],
          ['diff_bin', 'color', 'day_game_num'],
          ['diff_bin', 'color', 'game_time'],
          ['diff_bin', 'color', 'game_time', 'day_game_num'],
          ['diff_bin', 'color', 'game_time', 'weekday'],
          ['diff_bin', 'color', 'game_time', 'weekday', 'day_game_num'],
          ['diff_bin', 'color', 'time_bin'],
          ['diff_bin', 'color', 'time_bin', 'elo'],
          ['diff_bin', 'color', 'time_bin', 'elo', 'day_game_num'],
          ['diff_bin', 'color', 'time_bin', 'day_game_num'],
          ['diff_bin', 'color', 'time_bin', 'game_time'],
          ['diff_bin', 'color', 'time_bin', 'game_time', 'elo'],
          ['diff_bin', 'color', 'time_bin', 'game_time', 'elo', 'day_game_num'],
          ['diff_bin', 'color', 'time_bin', 'game_time', 'day_game_num'],
          ['diff_bin', 'color', 'time_bin', 'game_time', 'weekday'],
          ['diff_bin', 'color', 'time_bin', 'game_time', 'weekday', 'elo'],
          ['diff_bin', 'color', 'time_bin', 'game_time',
 'weekday', 'elo', 'day_game_num'],
          ['diff_bin', 'color', 'time_bin', 'game_time', 'weekday', 'day_game_num'],
          ['diff_bin', 'color', 'time_bin', 'weekday'],
          ['diff_bin', 'color', 'time_bin', 'weekday', 'elo'],
          ['diff_bin', 'color', 'time_bin', 'weekday', 'elo', 'day_game_num'],
          ['diff_bin', 'color', 'time_bin', 'weekday', 'day_game_num'],
          ['diff_bin', 'color', 'weekday'],
          ['diff_bin', 'color', 'weekday', 'day_game_num'],
          ['diff_bin', 'day_game_num'],
          ['diff_bin', 'game_time'],
          ['diff_bin', 'game_time', 'day_game_num'],
          ['diff_bin', 'game_time', 'weekday'],
          ['diff_bin', 'game_time', 'weekday', 'day_game_num'],
          ['diff_bin', 'time_bin'],
          ['diff_bin', 'time_bin', 'elo'],
          ['diff_bin', 'time_bin', 'elo', 'day_game_num'],
          ['diff_bin', 'time_bin', 'day_game_num'],
          ['diff_bin', 'time_bin', 'game_time'],
          ['diff_bin', 'time_bin', 'game_time', 'elo'],
          ['diff_bin', 'time_bin', 'game_time', 'elo', 'day_game_num'],
          ['diff_bin', 'time_bin', 'game_time', 'day_game_num'],
          ['diff_bin', 'time_bin', 'game_time', 'weekday'],
          ['diff_bin', 'time_bin', 'game_time', 'weekday', 'elo'],
          ['diff_bin', 'time_bin', 'game_time', 'weekday', 'elo', 'day_game_num'],
          ['diff_bin', 'time_bin', 'game_time', 'weekday', 'day_game_num'],
          ['diff_bin', 'time_bin', 'weekday'],
          [
 'diff_bin', 'time_bin', 'weekday', 'elo'],
          ['diff_bin', 'time_bin', 'weekday', 'elo', 'day_game_num'],
          ['diff_bin', 'time_bin', 'weekday', 'day_game_num'],
          ['diff_bin', 'weekday'],
          ['diff_bin', 'weekday', 'day_game_num']]

KNN_25 = [['diff_bin'],
          ['diff_bin', 'color', 'time_bin', 'weekday', 'day_game_num'],
          ['diff_bin', 'color', 'weekday', 'day_game_num'],
          ['diff_bin', 'day_game_num'],
          ['diff_bin', 'game_time'],
          ['diff_bin', 'game_time', 'day_game_num'],
          ['diff_bin', 'game_time', 'weekday', 'day_game_num'],
          ['diff_bin', 'time_bin', 'day_game_num'],
          ['diff_bin', 'time_bin', 'game_time'],
          ['diff_bin', 'time_bin', 'game_time', 'day_game_num'],
          ['diff_bin', 'time_bin', 'game_time', 'weekday'],
          ['diff_bin', 'time_bin', 'game_time', 'weekday', 'day_game_num'],
          ['diff_bin', 'time_bin', 'weekday', 'day_game_num'],
          ['diff_bin', 'weekday', 'day_game_num']]

KNN_200 = [['diff_bin', 'color', 'time_bin', 'weekday', 'day_game_num']]

KNN_167 = [['diff_bin', 'time_bin', 'weekday', 'day_game_num']]

KNN_125 = [['diff_bin', 'time_bin', 'day_game_num'],
          ['diff_bin', 'time_bin', 'game_time', 'weekday']]

KNN_111 = [['time_bin', 'weekday']]

KNN_091 = [['game_time', 'day_game_num'],
          ['game_time', 'weekday', 'day_game_num'],
          ['time_bin', 'game_time', 'weekday']]

KNN_067 = [['color', 'time_bin', 'game_time', 'day_game_num']]

GPC_25 = [['diff_bin', 'time_bin', 'day_game_num'],
          ['diff_bin', 'day_game_num'],
          ['diff_bin', 'time_bin'],
          ['diff_bin', 'game_time'],
          ['diff_bin'],
          ['diff_bin', 'color', 'time_bin', 'game_time'],
          ['diff_bin', 'game_time', 'day_game_num'],
          ['diff_bin', 'time_bin', 'game_time'],
          ['diff_bin', 'time_bin', 'game_time', 'day_game_num'],
          ['diff_bin', 'color', 'day_game_num'],
          ['diff_bin', 'color', 'time_bin', 'day_game_num'],
          ['diff_bin', 'color', 'time_bin'],
          ['diff_bin', 'time_bin', 'game_time', 'weekday', 'day_game_num'],
          ['diff_bin', 'time_bin', 'weekday', 'day_game_num'],
          ['diff_bin', 'color', 'time_bin', 'game_time', 'day_game_num'],
          ['diff_bin', 'color', 'game_time', 'day_game_num'],
          ['diff_bin', 'color', 'time_bin', 'weekday', 'day_game_num']]

GPC_200 = [['diff_bin', 'time_bin', 'day_game_num']]

GPC_125 = [['game_time', 'weekday']]

GPC_111 = [['game_time', 'weekday']]

GPC_100 = [['game_time', 'weekday']]

GPC_091 = [['weekday', 'day_game_num']]

LDA_25 = [['diff_bin', 'weekday', 'opp_elo'],
          ['diff_bin', 'weekday'],
          ['diff_bin', 'weekday', 'day_game_num'],
          ['diff_bin', 'weekday', 'elo', 'day_game_num'],
          ['diff_bin', 'time_bin', 'weekday', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'time_bin', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'time_bin', 'opp_elo'],
          ['diff_bin', 'time_bin', 'game_time', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'time_bin', 'game_time', 'elo', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'time_bin', 'day_game_num'],
          ['diff_bin', 'time_bin', 'elo', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'time_bin', 'elo', 'day_game_num'],
          ['diff_bin', 'time_bin', 'elo'],
          ['diff_bin', 'time_bin'],
          ['diff_bin', 'opp_elo'],
          ['diff_bin', 'game_time', 'weekday', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'game_time', 'weekday', 'opp_elo'],
          ['diff_bin', 'game_time', 'weekday'],
          ['diff_bin', 'game_time', 'opp_elo'],
          ['diff_bin', 'game_time', 'day_game_num'],
          ['diff_bin', 'game_time', 'elo', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'game_time', 'elo', 'opp_elo'],
          ['diff_bin', 'game_time', 'elo'],
          ['diff_bin', 'game_time'],
          ['diff_bin', 'day_game_num'],
          ['diff_bin', 'elo', 'day_game_num'],
          ['diff_bin', 'elo'],
          ['diff_bin', 'color', 'weekday', 'opp_elo'],
          ['diff_bin', 'color', 'weekday', 'day_game_num'],
          ['diff_bin', 'color', 'weekday'],
          ['diff_bin', 'color', 'time_bin', 'weekday', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'color', 'time_bin', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'color', 'time_bin', 'opp_elo'],
          ['diff_bin', 'color', 'time_bin', 'game_time',
 'weekday', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'color', 'time_bin', 'game_time', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'color', 'time_bin', 'game_time', 'opp_elo'],
          ['diff_bin', 'color', 'time_bin', 'game_time',
 'elo', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'color', 'time_bin', 'game_time', 'elo'],
          ['diff_bin', 'color', 'time_bin', 'game_time'],
          ['diff_bin', 'color', 'time_bin', 'elo', 'day_game_num'],
          ['diff_bin', 'color', 'time_bin', 'elo'],
          ['diff_bin', 'color', 'time_bin'],
          ['diff_bin', 'color', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'color', 'game_time', 'weekday', 'opp_elo'],
          ['diff_bin', 'color', 'game_time', 'weekday', 'day_game_num'],
          ['diff_bin', 'color', 'game_time', 'weekday'],
          ['diff_bin', 'color', 'game_time', 'opp_elo'],
          ['diff_bin', 'color', 'game_time', 'day_game_num'],
          ['diff_bin', 'color', 'game_time', 'elo', 'opp_elo'],
          ['diff_bin', 'color', 'game_time', 'elo'],
          ['diff_bin', 'color', 'game_time'],
          ['diff_bin', 'color', 'day_game_num'],
          ['diff_bin', 'color', 'elo', 'opp_elo'],
          ['diff_bin', 'color', 'elo', 'day_game_num'],
          ['diff_bin', 'color', 'elo'],
          ['diff_bin', 'color'],
          ['diff_bin']]

LDA_200 = [['diff_bin', 'color', 'game_time', 'weekday'],
          ['diff_bin', 'color', 'game_time', 'weekday', 'elo', 'opp_elo'],
          ['diff_bin', 'game_time', 'weekday', 'elo', 'opp_elo'],
          ['diff_bin', 'color', 'game_time', 'weekday', 'opp_elo'],
          ['diff_bin', 'game_time', 'weekday'],
          ['diff_bin', 'game_time', 'weekday', 'opp_elo'],
          ['diff_bin', 'weekday', 'opp_elo'],
          ['diff_bin', 'game_time', 'weekday', 'day_game_num'],
          ['diff_bin', 'color', 'game_time'],
          ['diff_bin', 'weekday'],
          ['diff_bin', 'color', 'weekday', 'opp_elo'],
          ['diff_bin', 'game_time'],
          ['diff_bin', 'time_bin', 'weekday'],
          ['diff_bin', 'color', 'weekday'],
          ['diff_bin', 'weekday', 'elo'],
          ['diff_bin', 'color', 'weekday', 'elo'],
          ['diff_bin', 'color', 'game_time', 'weekday', 'day_game_num'],
          ['diff_bin', 'time_bin', 'game_time', 'weekday', 'day_game_num'],
          ['diff_bin', 'color', 'weekday', 'day_game_num'],
          ['diff_bin', 'color', 'time_bin', 'game_time', 'weekday', 'day_game_num'],
          ['diff_bin', 'weekday', 'day_game_num'],
          ['diff_bin', 'color',
 'time_bin', 'game_time', 'weekday'],
          ['diff_bin', 'time_bin', 'weekday', 'day_game_num'],
          ['diff_bin', 'color', 'time_bin', 'weekday', 'day_game_num'],
          ['diff_bin', 'color', 'time_bin', 'weekday'],
          ['diff_bin', 'color', 'time_bin', 'game_time', 'day_game_num'],
          ['diff_bin', 'weekday', 'elo', 'opp_elo'],
          ['diff_bin', 'color', 'weekday', 'elo', 'opp_elo'],
          ['diff_bin', 'color'],
          ['diff_bin', 'color', 'time_bin'],
          ['diff_bin', 'time_bin', 'game_time', 'weekday', 'elo'],
          ['diff_bin', 'time_bin', 'game_time', 'day_game_num'],
          ['diff_bin', 'time_bin', 'game_time'],
          ['diff_bin', 'time_bin', 'game_time', 'weekday'],
          ['diff_bin', 'game_time', 'opp_elo'],
          ['diff_bin', 'time_bin', 'game_time', 'opp_elo'],
          ['diff_bin', 'time_bin'],
          ['diff_bin', 'color', 'time_bin', 'game_time', 'opp_elo'],
          ['diff_bin', 'color', 'time_bin', 'game_time', 'weekday', 'elo'],
          ['diff_bin'],
          ['diff_bin', 'color', 'game_time', 'day_game_num'],
          ['diff_bin', 'color', 'time_bin', 'game_time'],
          ['diff_bin', 'color', 'day_game_num']]

LDA_167 = [['diff_bin', 'weekday'],
          ['diff_bin', 'color', 'game_time', 'weekday'],
          ['diff_bin', 'game_time', 'weekday'],
          ['diff_bin', 'color', 'weekday'],
          ['diff_bin', 'color', 'game_time', 'weekday', 'day_game_num'],
          ['diff_bin', 'color', 'weekday', 'day_game_num'],
          ['diff_bin', 'weekday', 'day_game_num'],
          ['diff_bin', 'game_time', 'weekday', 'day_game_num'],
          ['diff_bin', 'color', 'game_time', 'weekday', 'opp_elo'],
          ['diff_bin', 'game_time', 'weekday', 'opp_elo'],
          ['diff_bin', 'time_bin', 'weekday'],
          ['diff_bin', 'time_bin', 'game_time', 'weekday'],
          ['diff_bin', 'color', 'time_bin', 'weekday'],
          ['diff_bin', 'time_bin', 'game_time',
              'weekday', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'color', 'time_bin', 'game_time',
 'weekday', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'weekday', 'opp_elo'],
          ['diff_bin', 'time_bin', 'game_time', 'weekday', 'elo'],
          ['diff_bin', 'time_bin', 'game_time', 'weekday', 'day_game_num'],
          ['diff_bin', 'color', 'time_bin', 'game_time', 'weekday'],
          ['diff_bin', 'color', 'weekday', 'opp_elo'],
          ['diff_bin', 'color', 'game_time'],
          ['diff_bin', 'time_bin', 'weekday', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'game_time'],
          ['diff_bin', 'color',
 'time_bin', 'game_time', 'weekday', 'day_game_num'],
          ['diff_bin', 'time_bin', 'weekday', 'opp_elo'],
          ['diff_bin', 'color', 'time_bin', 'weekday', 'elo', 'day_game_num'],
          ['diff_bin', 'time_bin', 'weekday', 'elo', 'day_game_num'],
          ['diff_bin', 'time_bin', 'weekday', 'elo'],
          ['diff_bin', 'game_time', 'day_game_num'],
          ['diff_bin', 'time_bin', 'game_time', 'weekday', 'opp_elo'],
          ['diff_bin', 'color', 'time_bin', 'weekday', 'elo'],
          ['diff_bin', 'color', 'game_time', 'day_game_num'],
          ['diff_bin', 'color', 'time_bin', 'game_time', 'weekday', 'elo'],
          ['diff_bin', 'color'],
          ['diff_bin', 'color', 'time_bin', 'weekday', 'opp_elo'],
          ['diff_bin', 'color', 'game_time', 'weekday', 'elo'],
          ['diff_bin', 'color', 'day_game_num'],
          ['diff_bin', 'color', 'time_bin', 'game_time', 'opp_elo'],
          ['diff_bin', 'color', 'time_bin', 'elo'],
          ['diff_bin', 'time_bin', 'elo'],
          ['diff_bin', 'game_time', 'opp_elo'],
          ['diff_bin', 'day_game_num'],
          ['diff_bin', 'game_time', 'weekday', 'elo', 'day_game_num'],
          ['diff_bin', 'color', 'game_time', 'weekday', 'elo', 'day_game_num'],
          ['diff_bin'],
          ['diff_bin', 'color', 'game_time', 'opp_elo'],
          ['diff_bin', 'color', 'weekday', 'elo', 'day_game_num']]

LDA_143 = [['game_time', 'weekday'],
          ['diff_bin', 'game_time', 'weekday'],
          ['diff_bin', 'time_bin', 'game_time', 'weekday'],
          ['diff_bin', 'color', 'game_time', 'weekday', 'day_game_num'],
          ['diff_bin', 'time_bin', 'weekday'],
          ['diff_bin', 'game_time', 'weekday', 'day_game_num'],
          ['diff_bin', 'color', 'time_bin', 'game_time', 'weekday'],
          ['diff_bin', 'color', 'game_time'],
          ['diff_bin', 'time_bin', 'game_time', 'weekday', 'day_game_num'],
          [
 'diff_bin', 'weekday'],
          ['diff_bin', 'color', 'game_time', 'day_game_num'],
          ['diff_bin', 'color', 'time_bin', 'weekday'],
          ['diff_bin', 'color', 'time_bin'],
          ['diff_bin', 'time_bin', 'weekday', 'day_game_num'],
          ['diff_bin', 'time_bin'],
          ['diff_bin', 'game_time', 'day_game_num'],
          ['diff_bin', 'color', 'weekday'],
          ['diff_bin', 'game_time'],
          ['diff_bin', 'color', 'weekday', 'day_game_num'],
          ['diff_bin', 'color'],
          ['diff_bin', 'day_game_num']]

LDA_125 = [['diff_bin', 'color', 'game_time', 'weekday'],
          ['diff_bin', 'game_time', 'weekday'],
          ['game_time', 'weekday'],
          ['color', 'game_time', 'weekday'],
          ['diff_bin', 'weekday'],
          ['diff_bin', 'color', 'game_time', 'weekday', 'day_game_num'],
          ['diff_bin', 'color', 'weekday', 'day_game_num'],
          ['diff_bin', 'weekday', 'day_game_num'],
          ['diff_bin', 'color', 'weekday'],
          ['diff_bin', 'game_time', 'weekday', 'day_game_num'],
          ['diff_bin', 'color', 'game_time'],
          ['diff_bin', 'game_time'],
          ['diff_bin', 'color', 'game_time', 'weekday', 'elo'],
          ['diff_bin', 'game_time', 'weekday', 'elo'],
          ['diff_bin', 'time_bin', 'game_time', 'weekday'],
          [
 'diff_bin', 'color', 'time_bin', 'game_time', 'weekday'],
          ['diff_bin', 'game_time', 'weekday', 'elo', 'day_game_num'],
          ['diff_bin', 'color', 'game_time', 'weekday', 'elo', 'day_game_num'],
          ['diff_bin', 'time_bin', 'game_time', 'weekday', 'day_game_num'],
          ['diff_bin', 'color', 'time_bin', 'game_time', 'weekday', 'day_game_num'],
          ['diff_bin', 'weekday', 'elo'],
          ['diff_bin', 'color'],
          ['diff_bin', 'elo'],
          ['diff_bin', 'color', 'elo'],
          ['diff_bin'],
          ['diff_bin', 'game_time', 'opp_elo'],
          ['diff_bin', 'color', 'time_bin', 'weekday', 'day_game_num'],
          ['diff_bin', 'time_bin', 'weekday'],
          ['diff_bin', 'color', 'time_bin', 'weekday']]

LDA_111 = [['diff_bin', 'game_time', 'weekday'],
          ['diff_bin', 'color', 'game_time', 'weekday'],
          ['game_time', 'weekday'],
          ['color', 'game_time', 'weekday'],
          ['diff_bin', 'game_time', 'weekday', 'day_game_num'],
          ['diff_bin', 'color', 'time_bin', 'game_time', 'weekday', 'day_game_num'],
          ['diff_bin', 'time_bin', 'weekday', 'day_game_num'],
          ['diff_bin', 'color', 'game_time', 'weekday', 'day_game_num'],
          ['diff_bin', 'color', 'weekday'],
          ['diff_bin', 'weekday'],
          ['diff_bin', 'time_bin', 'game_time', 'weekday',
 'day_game_num'],
          ['diff_bin', 'color', 'time_bin', 'weekday', 'day_game_num'],
          ['diff_bin', 'color', 'weekday', 'day_game_num'],
          ['diff_bin', 'weekday', 'day_game_num'],
          ['diff_bin', 'time_bin'],
          ['diff_bin', 'color', 'game_time'],
          ['diff_bin', 'game_time'],
          ['diff_bin', 'color', 'time_bin'],
          ['diff_bin', 'time_bin', 'game_time', 'day_game_num'],
          ['diff_bin', 'time_bin', 'day_game_num'],
          ['diff_bin', 'color'],
          ['diff_bin', 'color', 'time_bin', 'day_game_num'],
          ['diff_bin', 'time_bin', 'weekday']]

LDA_100 = [['game_time', 'weekday'],
          ['color', 'game_time', 'weekday'],
          ['diff_bin', 'game_time', 'weekday'],
          ['diff_bin', 'color', 'weekday'],
          ['diff_bin', 'color', 'game_time', 'weekday'],
          ['diff_bin', 'color',
 'game_time', 'day_game_num'],
          ['diff_bin', 'game_time', 'weekday', 'day_game_num'],
          ['diff_bin', 'weekday'],
          ['diff_bin', 'color', 'day_game_num'],
          ['diff_bin', 'game_time', 'day_game_num'],
          ['diff_bin', 'day_game_num']]

LDA_091 = [['color', 'game_time', 'weekday', 'day_game_num'],
          ['diff_bin', 'time_bin', 'game_time', 'weekday', 'day_game_num'],
          ['diff_bin', 'color', 'game_time', 'weekday', 'elo'],
          ['game_time', 'weekday'],
          ['game_time', 'weekday', 'day_game_num'],
          ['diff_bin', 'game_time', 'weekday'],
          ['diff_bin', 'time_bin', 'weekday', 'day_game_num'],
          ['diff_bin', 'weekday'],
          ['diff_bin', 'color', 'game_time', 'weekday', 'day_game_num'],
          ['diff_bin', 'color', 'game_time'],
          ['diff_bin', 'time_bin'],
          ['diff_bin', 'color', 'weekday'],
          ['diff_bin', 'time_bin', 'game_time', 'day_game_num'],
          ['diff_bin', 'color'],
          ['diff_bin', 'time_bin', 'day_game_num'],
          ['diff_bin', 'color', 'game_time', 'weekday'],
          ['diff_bin', 'time_bin', 'game_time', 'weekday'],
          ['diff_bin', 'game_time'],
          ['diff_bin', 'game_time', 'weekday', 'day_game_num'],
          ['diff_bin', 'color', 'weekday', 'day_game_num'],
          ['diff_bin', 'game_time', 'day_game_num'],
          [
 'diff_bin', 'weekday', 'day_game_num'],
          ['diff_bin', 'color', 'time_bin', 'game_time',
 'weekday', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'color', 'time_bin', 'game_time'],
          ['diff_bin', 'color', 'game_time', 'day_game_num'],
          ['diff_bin', 'color', 'time_bin', 'game_time', 'weekday', 'day_game_num'],
          ['diff_bin', 'color', 'time_bin', 'game_time', 'day_game_num'],
          ['diff_bin', 'time_bin', 'game_time', 'weekday', 'elo', 'day_game_num'],
          ['diff_bin', 'time_bin', 'game_time',
              'weekday', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'time_bin', 'game_time', 'weekday', 'elo'],
          ['diff_bin', 'day_game_num'],
          ['diff_bin', 'time_bin', 'weekday', 'elo'],
          ['diff_bin', 'color', 'time_bin', 'weekday', 'opp_elo'],
          ['diff_bin', 'time_bin', 'game_time', 'elo', 'day_game_num'],
          ['diff_bin', 'color', 'time_bin'],
          ['diff_bin', 'time_bin', 'game_time'],
          ['diff_bin', 'color', 'time_bin', 'game_time', 'weekday', 'opp_elo']]

LDA_067 = [['diff_bin', 'time_bin', 'game_time', 'weekday', 'day_game_num'],
          ['diff_bin', 'time_bin', 'game_time', 'weekday'],
          ['diff_bin', 'color', 'time_bin', 'game_time', 'weekday', 'day_game_num'],
          ['diff_bin', 'color', 'time_bin', 'game_time', 'weekday'],
          ['diff_bin', 'color', 'time_bin', 'weekday'],
          ['game_time', 'weekday', 'day_game_num'],
          ['diff_bin', 'time_bin', 'weekday', 'day_game_num'],
          ['diff_bin', 'color', 'weekday', 'day_game_num'],
          ['diff_bin', 'game_time', 'weekday', 'day_game_num'],
          ['diff_bin', 'color', 'game_time', 'weekday', 'day_game_num'],
          ['diff_bin', 'time_bin', 'weekday'],
          ['diff_bin', 'color', 'time_bin', 'weekday', 'day_game_num'],
          ['diff_bin', 'game_time', 'weekday'],
          ['diff_bin', 'color', 'game_time', 'weekday'],
          ['diff_bin', 'weekday']]

SGD_25 = [['diff_bin'],
          ['diff_bin', 'color', 'game_time', 'weekday'],
          ['diff_bin', 'color', 'time_bin', 'game_time'],
          ['diff_bin', 'color', 'time_bin', 'game_time', 'day_game_num'],
          ['diff_bin', 'color', 'time_bin', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'color', 'time_bin', 'weekday'],
          ['diff_bin', 'color', 'weekday'],
          ['diff_bin', 'color', 'weekday', 'day_game_num'],
          ['diff_bin', 'color', 'weekday', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'game_time'],
          ['diff_bin', 'game_time', 'day_game_num'],
          ['diff_bin', 'game_time', 'weekday'],
          ['diff_bin', 'opp_elo'],
          ['diff_bin', 'time_bin', 'day_game_num'],
          ['diff_bin', 'time_bin', 'game_time'],
          ['diff_bin', 'time_bin', 'game_time', 'day_game_num'],
          ['diff_bin', 'time_bin', 'game_time', 'weekday', 'elo', 'day_game_num'],
          ['diff_bin', 'time_bin', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'weekday'],
          ['diff_bin', 'weekday', 'opp_elo', 'day_game_num']]

SGD_200 = [['diff_bin'],
          ['diff_bin', 'color', 'game_time', 'weekday'],
          ['diff_bin', 'color', 'weekday', 'day_game_num'],
          ['diff_bin', 'game_time'],
          ['diff_bin', 'game_time', 'day_game_num'],
          ['diff_bin', 'game_time', 'weekday'],
          ['diff_bin', 'time_bin', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'weekday', 'day_game_num'],
          ['diff_bin', 'day_game_num'],
          ['diff_bin', 'color', 'game_time', 'weekday', 'day_game_num'],
          ['diff_bin', 'color'],
          ['diff_bin', 'color', 'game_time'],
          ['diff_bin', 'time_bin', 'game_time', 'weekday']]

SGD_167 = [['diff_bin', 'color', 'time_bin', 'game_time', 'day_game_num'],
          ['diff_bin', 'game_time'],
          ['diff_bin', 'game_time', 'day_game_num'],
          ['diff_bin', 'game_time', 'weekday'],
          ['diff_bin', 'weekday'],
          ['diff_bin', 'weekday', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'time_bin', 'elo', 'opp_elo'],
          ['diff_bin', 'time_bin', 'game_time', 'opp_elo'],
          ['diff_bin', 'color', 'game_time', 'weekday', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'time_bin', 'weekday', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'game_time', 'weekday', 'opp_elo'],
          ['diff_bin', 'color', 'weekday', 'elo'],
          ['diff_bin', 'color', 'time_bin', 'elo', 'opp_elo'],
          ['diff_bin', 'color', 'elo', 'opp_elo'],
          ['diff_bin', 'color', 'game_time', 'elo', 'opp_elo'],
          ['diff_bin', 'weekday', 'elo', 'opp_elo'],
          ['diff_bin', 'color', 'time_bin', 'game_time',
 'weekday', 'elo', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'color', 'elo', 'day_game_num'],
          ['diff_bin', 'color', 'game_time', 'weekday',
              'elo', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'time_bin', 'game_time', 'elo'],
          ['diff_bin', 'color', 'elo'],
          ['diff_bin', 'time_bin', 'weekday', 'elo', 'opp_elo', 'day_game_num']]

SGD_143 = [['diff_bin', 'color', 'game_time', 'weekday'],
          ['diff_bin', 'time_bin', 'game_time'],
          ['diff_bin', 'color', 'time_bin', 'day_game_num'],
          ['diff_bin', 'time_bin'],
          ['diff_bin', 'color', 'game_time', 'elo', 'day_game_num'],
          ['diff_bin', 'color', 'time_bin', 'game_time', 'elo']]

SGD_125 = [['diff_bin', 'color', 'weekday', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'time_bin', 'day_game_num'],
          ['diff_bin', 'color', 'time_bin'],
          ['diff_bin', 'time_bin', 'elo', 'opp_elo'],
          ['diff_bin', 'color', 'time_bin', 'game_time', 'elo', 'opp_elo'],
          ['diff_bin', 'time_bin', 'weekday', 'opp_elo'],
          ['diff_bin', 'color', 'time_bin', 'game_time', 'weekday', 'elo', 'opp_elo'],
          ['diff_bin', 'color', 'time_bin', 'weekday',
              'elo', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'elo', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'time_bin', 'weekday', 'elo', 'opp_elo']]

SGD_111 = [['diff_bin', 'color', 'game_time', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'game_time', 'weekday', 'elo', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'color', 'time_bin', 'game_time', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'color', 'game_time', 'elo']]

SGD_091 = [['diff_bin', 'color', 'time_bin', 'game_time', 'day_game_num'],
          ['diff_bin', 'weekday', 'day_game_num'],
          ['diff_bin', 'day_game_num'],
          ['diff_bin', 'color', 'time_bin', 'day_game_num']]

RDG_25 = [['diff_bin'],
          ['diff_bin', 'color', 'elo', 'opp_elo'],
          ['diff_bin', 'color', 'elo', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'color', 'day_game_num'],
          ['diff_bin', 'color', 'game_time'],
          ['diff_bin', 'color', 'game_time', 'elo'],
          ['diff_bin', 'color', 'game_time', 'elo', 'opp_elo'],
          ['diff_bin', 'color', 'game_time', 'elo', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'color', 'game_time', 'day_game_num'],
          ['diff_bin', 'color', 'game_time', 'opp_elo'],
          ['diff_bin', 'color', 'game_time', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'color', 'game_time', 'weekday'],
          ['diff_bin', 'color', 'game_time', 'weekday', 'elo', 'opp_elo'],
          ['diff_bin', 'color', 'game_time', 'weekday',
              'elo', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'color', 'game_time', 'weekday', 'day_game_num'],
          ['diff_bin', 'color', 'game_time', 'weekday', 'opp_elo'],
          ['diff_bin', 'color', 'game_time', 'weekday', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'color', 'opp_elo'],
          ['diff_bin', 'color', 'time_bin', 'game_time', 'elo', 'opp_elo'],
          ['diff_bin', 'color', 'time_bin', 'game_time', 'opp_elo'],
          ['diff_bin', 'color', 'time_bin', 'game_time', 'weekday'],
          ['diff_bin', 'color', 'time_bin', 'game_time', 'weekday', 'elo', 'opp_elo'],
          ['diff_bin', 'color', 'time_bin', 'opp_elo'],
          ['diff_bin', 'color', 'time_bin', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'color', 'time_bin', 'weekday'],
          ['diff_bin', 'color', 'time_bin', 'weekday', 'elo', 'opp_elo'],
          ['diff_bin', 'color',
 'time_bin', 'weekday', 'day_game_num'],
          ['diff_bin', 'color', 'weekday'],
          ['diff_bin', 'color', 'weekday', 'elo', 'opp_elo'],
          ['diff_bin', 'color', 'weekday', 'day_game_num'],
          ['diff_bin', 'color', 'weekday', 'opp_elo'],
          ['diff_bin', 'color', 'weekday', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'elo', 'opp_elo'],
          ['diff_bin', 'elo', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'day_game_num'],
          ['diff_bin', 'game_time'],
          ['diff_bin', 'game_time', 'elo', 'day_game_num'],
          ['diff_bin', 'game_time', 'elo', 'opp_elo'],
          ['diff_bin', 'game_time', 'elo', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'game_time', 'day_game_num'],
          ['diff_bin', 'game_time', 'opp_elo'],
          ['diff_bin', 'game_time', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'game_time', 'weekday'],
          ['diff_bin', 'game_time', 'weekday', 'elo', 'opp_elo'],
          ['diff_bin', 'game_time', 'weekday', 'elo', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'game_time', 'weekday', 'day_game_num'],
          ['diff_bin', 'game_time', 'weekday', 'opp_elo'],
          ['diff_bin', 'game_time', 'weekday', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'opp_elo'],
          ['diff_bin', 'time_bin', 'elo', 'opp_elo'],
          ['diff_bin', 'time_bin', 'game_time', 'opp_elo'],
          ['diff_bin', 'time_bin', 'opp_elo'],
          ['diff_bin', 'weekday'],
          ['diff_bin', 'weekday', 'elo', 'opp_elo'],
          ['diff_bin', 'weekday', 'elo', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'weekday', 'day_game_num'],
          ['diff_bin', 'weekday', 'opp_elo'],
          ['diff_bin', 'weekday', 'opp_elo', 'day_game_num']]

RDG_200 = [['diff_bin'],
          ['diff_bin', 'color', 'day_game_num'],
          ['diff_bin', 'color', 'game_time', 'opp_elo'],
          ['diff_bin', 'color', 'game_time', 'weekday'],
          ['diff_bin', 'color', 'game_time', 'weekday', 'elo', 'opp_elo'],
          ['diff_bin', 'color', 'game_time', 'weekday', 'day_game_num'],
          ['diff_bin', 'color', 'game_time', 'weekday', 'opp_elo'],
          ['diff_bin', 'color', 'game_time', 'weekday', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'color', 'opp_elo'],
          ['diff_bin', 'color', 'time_bin', 'game_time', 'weekday'],
          ['diff_bin', 'color', 'time_bin', 'weekday'],
          ['diff_bin', 'color', 'weekday'],
          ['diff_bin', 'color', 'weekday', 'elo', 'opp_elo'],
          ['diff_bin', 'color', 'weekday', 'opp_elo'],
          ['diff_bin', 'color', 'weekday', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'day_game_num'],
          ['diff_bin', 'game_time'],
          ['diff_bin', 'game_time', 'opp_elo'],
          ['diff_bin', 'game_time', 'opp_elo', 'day_game_num'],
          [
 'diff_bin', 'game_time', 'weekday'],
          ['diff_bin', 'game_time', 'weekday', 'elo', 'opp_elo'],
          ['diff_bin', 'game_time', 'weekday', 'day_game_num'],
          ['diff_bin', 'game_time', 'weekday', 'opp_elo'],
          ['diff_bin', 'game_time', 'weekday', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'opp_elo'],
          ['diff_bin', 'weekday'],
          ['diff_bin', 'weekday', 'elo', 'opp_elo'],
          ['diff_bin', 'weekday', 'day_game_num'],
          ['diff_bin', 'weekday', 'opp_elo'],
          ['diff_bin', 'weekday', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'color', 'game_time', 'weekday', 'elo'],
          ['diff_bin', 'color', 'weekday', 'elo'],
          ['diff_bin', 'color', 'time_bin', 'game_time', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'color', 'time_bin', 'game_time', 'weekday', 'opp_elo'],
          ['diff_bin', 'color', 'time_bin', 'weekday', 'opp_elo'],
          ['diff_bin', 'time_bin', 'game_time', 'weekday'],
          ['diff_bin', 'game_time', 'weekday', 'elo'],
          ['diff_bin', 'opp_elo', 'day_game_num']]

RDG_167 = [['diff_bin'],
          ['diff_bin', 'color', 'elo', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'color', 'day_game_num'],
          ['diff_bin', 'color', 'game_time'],
          ['diff_bin', 'color', 'game_time', 'elo', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'color', 'game_time', 'opp_elo'],
          ['diff_bin', 'color', 'game_time', 'weekday'],
          ['diff_bin', 'color', 'game_time', 'weekday', 'elo', 'opp_elo'],
          ['diff_bin', 'color', 'game_time', 'weekday', 'day_game_num'],
          ['diff_bin', 'color', 'game_time', 'weekday', 'opp_elo'],
          ['diff_bin', 'color', 'game_time', 'weekday', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'color', 'opp_elo'],
          ['diff_bin', 'color', 'time_bin', 'game_time', 'weekday'],
          ['diff_bin', 'color', 'time_bin', 'opp_elo'],
          ['diff_bin', 'color', 'time_bin', 'weekday'],
          ['diff_bin', 'color', 'weekday'],
          ['diff_bin', 'color', 'weekday', 'elo', 'opp_elo'],
          ['diff_bin', 'color', 'weekday', 'day_game_num'],
          ['diff_bin', 'color', 'weekday', 'opp_elo'],
          ['diff_bin', 'color', 'weekday', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'elo', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'day_game_num'],
          ['diff_bin', 'game_time'],
          ['diff_bin', 'game_time', 'elo', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'game_time', 'opp_elo'],
          ['diff_bin', 'game_time', 'weekday'],
          ['diff_bin', 'game_time', 'weekday',
 'elo', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'game_time', 'weekday', 'day_game_num'],
          ['diff_bin', 'game_time', 'weekday', 'opp_elo'],
          ['diff_bin', 'game_time', 'weekday', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'opp_elo'],
          ['diff_bin', 'weekday'],
          ['diff_bin', 'weekday', 'day_game_num'],
          ['diff_bin', 'weekday', 'opp_elo'],
          ['diff_bin', 'weekday', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'color', 'time_bin', 'game_time', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'color', 'time_bin', 'game_time', 'weekday', 'opp_elo'],
          ['diff_bin', 'color', 'time_bin', 'weekday', 'elo', 'day_game_num'],
          ['diff_bin', 'color', 'time_bin', 'weekday', 'opp_elo'],
          ['diff_bin', 'color', 'time_bin', 'weekday', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'time_bin', 'game_time', 'weekday'],
          ['diff_bin', 'time_bin', 'game_time', 'weekday', 'elo', 'opp_elo'],
          ['diff_bin', 'time_bin', 'game_time', 'weekday', 'opp_elo'],
          ['diff_bin', 'time_bin', 'game_time',
              'weekday', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'time_bin', 'weekday'],
          ['diff_bin', 'time_bin', 'weekday', 'elo', 'opp_elo'],
          ['diff_bin', 'time_bin', 'weekday', 'day_game_num'],
          ['diff_bin', 'time_bin', 'weekday', 'opp_elo'],
          ['diff_bin', 'time_bin', 'weekday', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'color', 'time_bin', 'game_time']]

RDG_143 = [['diff_bin', 'color', 'game_time'],
          ['diff_bin', 'color', 'game_time', 'elo', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'color', 'game_time', 'opp_elo'],
          ['diff_bin', 'color', 'game_time', 'weekday'],
          ['diff_bin', 'color', 'game_time', 'weekday',
              'elo', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'color', 'game_time', 'weekday', 'day_game_num'],
          ['diff_bin', 'color', 'game_time', 'weekday', 'opp_elo'],
          ['diff_bin', 'color', 'game_time', 'weekday', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'color', 'time_bin', 'opp_elo'],
          ['diff_bin', 'color', 'weekday', 'day_game_num'],
          ['diff_bin', 'color', 'weekday', 'opp_elo'],
          ['diff_bin', 'color', 'weekday', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'game_time'],
          ['diff_bin', 'game_time', 'elo',
 'day_game_num'],
          ['diff_bin', 'game_time', 'elo', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'game_time', 'day_game_num'],
          ['diff_bin', 'game_time', 'opp_elo'],
          ['diff_bin', 'game_time', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'game_time', 'weekday'],
          ['diff_bin', 'game_time', 'weekday', 'day_game_num'],
          ['diff_bin', 'game_time', 'weekday', 'opp_elo'],
          ['diff_bin', 'game_time', 'weekday', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'time_bin', 'opp_elo'],
          ['diff_bin', 'weekday', 'day_game_num'],
          ['diff_bin', 'weekday', 'opp_elo'],
          ['diff_bin', 'weekday', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'color', 'time_bin', 'game_time'],
          ['diff_bin', 'time_bin', 'game_time'],
          ['diff_bin', 'color', 'game_time', 'weekday', 'elo', 'day_game_num']]

RDG_125 = [['diff_bin'],
          ['diff_bin', 'color', 'elo', 'opp_elo'],
          ['diff_bin', 'color', 'elo', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'color', 'game_time', 'opp_elo'],
          ['diff_bin', 'color', 'game_time', 'weekday'],
          ['diff_bin', 'color', 'game_time', 'weekday', 'elo', 'opp_elo'],
          ['diff_bin', 'color', 'game_time', 'weekday',
              'elo', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'color', 'game_time', 'weekday', 'day_game_num'],
          ['diff_bin', 'color', 'game_time', 'weekday', 'opp_elo'],
          ['diff_bin', 'color', 'game_time', 'weekday', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'color', 'weekday'],
          ['diff_bin', 'color', 'weekday', 'day_game_num'],
          ['diff_bin', 'color', 'weekday', 'opp_elo'],
          ['diff_bin', 'color', 'weekday', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'elo', 'opp_elo'],
          ['diff_bin', 'elo', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'game_time'],
          ['diff_bin', 'game_time', 'elo', 'day_game_num'],
          [
 'diff_bin', 'game_time', 'elo', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'game_time', 'opp_elo'],
          ['diff_bin', 'game_time', 'weekday'],
          ['diff_bin', 'game_time', 'weekday', 'elo', 'opp_elo'],
          ['diff_bin', 'game_time', 'weekday', 'elo', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'game_time', 'weekday', 'day_game_num'],
          ['diff_bin', 'game_time', 'weekday', 'opp_elo'],
          ['diff_bin', 'game_time', 'weekday', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'opp_elo'],
          ['diff_bin', 'weekday', 'elo', 'opp_elo'],
          ['diff_bin', 'weekday', 'elo', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'weekday', 'day_game_num'],
          ['diff_bin', 'weekday', 'opp_elo'],
          ['diff_bin', 'weekday', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'color', 'game_time', 'weekday', 'elo', 'day_game_num'],
          ['diff_bin', 'color', 'weekday', 'elo', 'day_game_num'],
          ['diff_bin', 'elo'],
          ['diff_bin', 'game_time', 'weekday', 'elo', 'day_game_num']]

RDG_111 = [['diff_bin', 'color', 'game_time', 'weekday'],
          ['diff_bin', 'color', 'game_time', 'weekday', 'day_game_num'],
          ['diff_bin', 'color', 'weekday'],
          ['diff_bin', 'color',
 'weekday', 'day_game_num'],
          ['diff_bin', 'game_time', 'weekday'],
          ['diff_bin', 'game_time', 'weekday', 'day_game_num'],
          ['diff_bin', 'weekday'],
          ['diff_bin', 'weekday', 'day_game_num']]

RDG_100 = [['diff_bin', 'color', 'game_time', 'weekday'],
          ['diff_bin', 'color', 'game_time', 'weekday', 'day_game_num'],
          ['diff_bin', 'color', 'game_time', 'weekday', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'day_game_num'],
          [
 'diff_bin', 'game_time', 'weekday'],
          ['diff_bin', 'game_time', 'weekday', 'day_game_num'],
          ['diff_bin', 'game_time', 'weekday', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'opp_elo', 'day_game_num']]

RDG_091 = [['diff_bin', 'color', 'elo', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'color', 'day_game_num'],
          ['diff_bin', 'color', 'game_time'],
          ['diff_bin', 'color', 'game_time', 'elo', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'color', 'game_time', 'day_game_num'],
          ['diff_bin', 'color', 'game_time', 'opp_elo'],
          ['diff_bin', 'color', 'game_time', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'color', 'game_time', 'weekday'],
          ['diff_bin', 'color', 'game_time', 'weekday',
              'elo', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'color', 'game_time', 'weekday', 'day_game_num'],
          ['diff_bin', 'color', 'game_time', 'weekday', 'opp_elo'],
          ['diff_bin', 'color', 'game_time', 'weekday', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'color', 'opp_elo'],
          ['diff_bin', 'color', 'weekday'],
          ['diff_bin', 'color', 'weekday', 'day_game_num'],
          ['diff_bin', 'color', 'weekday', 'opp_elo'],
          ['diff_bin', 'day_game_num'],
          [
 'diff_bin', 'game_time'],
          ['diff_bin', 'game_time', 'elo', 'day_game_num'],
          ['diff_bin', 'game_time', 'elo', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'game_time', 'day_game_num'],
          ['diff_bin', 'game_time', 'opp_elo'],
          ['diff_bin', 'game_time', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'game_time', 'weekday'],
          ['diff_bin', 'game_time', 'weekday', 'day_game_num'],
          ['diff_bin', 'game_time', 'weekday', 'opp_elo'],
          ['diff_bin', 'game_time', 'weekday', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'weekday'],
          ['diff_bin', 'weekday', 'day_game_num'],
          ['diff_bin', 'weekday', 'opp_elo'],
          ['diff_bin', 'weekday', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'color'],
          ['diff_bin', 'color', 'elo', 'day_game_num'],
          ['diff_bin', 'color', 'game_time', 'elo', 'day_game_num'],
          ['diff_bin', 'color', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'game_time', 'weekday', 'elo'],
          ['diff_bin', 'opp_elo', 'day_game_num']]

RFC_25 = [['diff_bin'],
          ['diff_bin', 'color', 'elo'],
          ['diff_bin', 'color', 'game_time', 'day_game_num'],
          ['diff_bin', 'color', 'game_time', 'opp_elo'],
          ['diff_bin', 'color', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'color', 'time_bin', 'elo'],
          ['diff_bin', 'color', 'time_bin', 'elo', 'day_game_num'],
          ['diff_bin', 'color', 'time_bin', 'game_time', 'elo'],
          ['diff_bin', 'color', 'time_bin', 'game_time', 'elo', 'opp_elo'],
          ['diff_bin', 'color', 'time_bin', 'game_time',
              'elo', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'color', 'time_bin', 'game_time', 'weekday', 'elo'],
          ['diff_bin', 'color', 'time_bin', 'game_time', 'weekday', 'opp_elo'],
          ['diff_bin', 'color', 'time_bin', 'opp_elo',
 'day_game_num'],
          ['diff_bin', 'game_time'],
          ['diff_bin', 'game_time', 'opp_elo'],
          ['diff_bin', 'time_bin'],
          ['diff_bin', 'time_bin', 'day_game_num'],
          ['diff_bin', 'time_bin', 'game_time', 'elo', 'day_game_num'],
          ['diff_bin', 'time_bin', 'game_time', 'opp_elo'],
          ['diff_bin', 'time_bin', 'game_time', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'time_bin', 'game_time', 'weekday', 'elo'],
          ['diff_bin', 'time_bin', 'game_time', 'weekday', 'elo', 'opp_elo'],
          ['diff_bin', 'time_bin', 'game_time', 'weekday',
 'elo', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'time_bin', 'game_time', 'weekday', 'opp_elo'],
          ['diff_bin', 'time_bin', 'opp_elo'],
          ['diff_bin', 'time_bin', 'opp_elo', 'day_game_num']]

RFC_200 = [['diff_bin', 'color', 'game_time', 'weekday', 'opp_elo'],
          ['diff_bin', 'color', 'time_bin'],
          ['diff_bin', 'color', 'weekday', 'day_game_num'],
          [
 'diff_bin', 'game_time', 'opp_elo'],
          ['diff_bin', 'time_bin', 'game_time'],
          ['diff_bin', 'time_bin', 'opp_elo'],
          ['diff_bin', 'weekday', 'opp_elo', 'day_game_num']]

RFC_167 = [['diff_bin', 'color', 'day_game_num'],
          ['diff_bin', 'color', 'game_time'],
          ['diff_bin', 'color', 'time_bin', 'weekday', 'elo'],
          ['diff_bin', 'game_time',
 'opp_elo'],
          ['diff_bin', 'time_bin', 'elo'],
          ['diff_bin', 'time_bin', 'game_time', 'weekday', 'day_game_num'],
          ['diff_bin', 'time_bin', 'weekday', 'elo']]

RFC_143 = [['diff_bin', 'game_time', 'day_game_num']]

RFC_125 = [['diff_bin', 'color', 'game_time', 'opp_elo'],
          ['diff_bin', 'color', 'weekday', 'day_game_num'],
          [
 'diff_bin', 'day_game_num'],
          ['diff_bin', 'game_time', 'day_game_num'],
          ['diff_bin', 'game_time', 'opp_elo']]

RFC_111 = [['diff_bin', 'color', 'time_bin', 'game_time', 'weekday', 'elo']]

RFC_091 = [['diff_bin', 'color', 'game_time', 'day_game_num'],
          ['diff_bin', 'color', 'game_time', 'weekday', 'opp_elo',
 'day_game_num'],
          ['diff_bin', 'game_time', 'day_game_num'],
          ['diff_bin', 'game_time', 'weekday', 'opp_elo']]

LRC_25 = [['diff_bin', 'color', 'time_bin', 'game_time', 'weekday', 'elo'],
          ['diff_bin', 'color', 'time_bin', 'game_time',
              'weekday', 'elo', 'day_game_num'],
          ['diff_bin', 'color', 'time_bin', 'weekday', 'elo'],
          ['diff_bin', 'color', 'time_bin', 'game_time', 'elo'],
          ['diff_bin', 'color', 'time_bin', 'weekday', 'elo', 'day_game_num'],
          ['diff_bin', 'time_bin', 'elo'],
          ['diff_bin', 'time_bin', 'elo', 'day_game_num'],
          ['diff_bin', 'time_bin', 'game_time', 'elo'],
          ['diff_bin', 'time_bin', 'game_time', 'elo', 'day_game_num'],
          ['diff_bin', 'time_bin', 'game_time', 'weekday', 'elo', 'day_game_num'],
          ['diff_bin', 'time_bin', 'weekday', 'elo'],
          ['diff_bin', 'time_bin', 'weekday', 'elo', 'day_game_num'],
          ['diff_bin', 'color', 'game_time', 'weekday', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'color', 'weekday', 'opp_elo'],
          ['diff_bin', 'color', 'game_time', 'elo'],
          ['diff_bin', 'color', 'game_time', 'elo', 'day_game_num'],
          ['diff_bin', 'color', 'game_time', 'weekday', 'elo'],
          ['diff_bin', 'color', 'game_time', 'weekday', 'elo', 'day_game_num'],
          ['diff_bin', 'color', 'time_bin', 'elo'],
          ['diff_bin', 'color', 'time_bin', 'elo', 'day_game_num'],
          ['diff_bin', 'color', 'time_bin', 'game_time', 'elo', 'day_game_num'],
          ['diff_bin', 'color', 'weekday', 'elo'],
          ['diff_bin', 'color', 'weekday', 'elo', 'day_game_num'],
          ['diff_bin', 'elo'],
          ['diff_bin', 'game_time', 'elo'],
          ['diff_bin', 'game_time', 'elo', 'day_game_num'],
          ['diff_bin', 'game_time', 'weekday', 'elo'],
          ['diff_bin', 'game_time', 'weekday', 'elo', 'day_game_num'],
          ['diff_bin', 'weekday', 'elo'],
          ['diff_bin', 'weekday', 'elo', 'day_game_num'],
          ['diff_bin', 'color', 'time_bin', 'game_time',
 'weekday', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'color', 'time_bin', 'weekday', 'opp_elo'],
          ['diff_bin', 'color', 'time_bin', 'weekday', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'color', 'weekday', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'game_time', 'weekday', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'time_bin', 'game_time',
              'weekday', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'time_bin', 'weekday', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'weekday', 'opp_elo', 'day_game_num'],
          ['diff_bin',
 'color', 'elo', 'day_game_num'],
          ['diff_bin', 'elo', 'day_game_num'],
          ['diff_bin', 'color', 'elo', 'opp_elo'],
          ['diff_bin', 'color', 'elo', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'color', 'game_time', 'elo', 'opp_elo'],
          ['diff_bin', 'color', 'game_time', 'elo', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'color', 'game_time', 'weekday', 'elo', 'opp_elo'],
          ['diff_bin', 'color', 'time_bin', 'elo', 'opp_elo'],
          ['diff_bin', 'color', 'time_bin', 'elo', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'color', 'time_bin', 'game_time', 'elo', 'opp_elo'],
          ['diff_bin', 'color', 'time_bin', 'game_time',
              'elo', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'color', 'time_bin', 'game_time', 'weekday', 'elo', 'opp_elo'],
          ['diff_bin', 'color', 'time_bin', 'game_time',
 'weekday', 'elo', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'color', 'time_bin', 'weekday', 'elo', 'opp_elo'],
          ['diff_bin', 'color', 'time_bin', 'weekday',
              'elo', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'color', 'weekday', 'elo', 'opp_elo'],
          ['diff_bin', 'color', 'weekday', 'elo', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'elo', 'opp_elo'],
          ['diff_bin', 'elo', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'game_time', 'elo', 'opp_elo'],
          ['diff_bin', 'game_time', 'elo', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'game_time', 'weekday', 'elo', 'opp_elo'],
          ['diff_bin', 'game_time', 'weekday', 'elo', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'time_bin', 'elo', 'opp_elo'],
          ['diff_bin', 'time_bin', 'elo', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'time_bin', 'game_time', 'elo', 'opp_elo'],
          ['diff_bin', 'time_bin', 'game_time', 'elo', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'time_bin', 'game_time', 'weekday', 'elo', 'opp_elo'],
          ['diff_bin', 'time_bin', 'game_time', 'weekday',
 'elo', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'time_bin', 'weekday', 'elo', 'opp_elo'],
          ['diff_bin', 'time_bin', 'weekday', 'elo', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'weekday', 'elo', 'opp_elo'],
          ['diff_bin', 'weekday', 'elo', 'opp_elo', 'day_game_num'],
          ['diff_bin', 'color', 'elo'],
          ['diff_bin', 'time_bin', 'game_time', 'weekday', 'elo'],
          ['diff_bin', 'color', 'game_time', 'weekday', 'elo', 'opp_elo', 'day_game_num']]

LRC_200 = [['diff_bin']]

LRC_167 = [['diff_bin']]

LRC_125 = [['game_time', 'weekday'],
          ['diff_bin']]

LRC_111 = [['game_time', 'weekday']]

LRC_100 = [['game_time', 'weekday']]

LRC_091 = [['game_time', 'weekday', 'day_game_num']]