all_cols = [
    ['diff', 'color', 'time', 'game_time',
        'weekday', 'elo', 'opp_elo', 'game_num'],
    ['diff', 'color', 'time', 'game_time', 'weekday', 'elo', 'opp_elo'],
    ['diff', 'color', 'time', 'game_time', 'weekday', 'elo', 'game_num'],
    ['diff', 'color', 'time', 'game_time', 'weekday', 'opp_elo', 'game_num'],
    ['diff', 'color', 'time', 'game_time', 'elo', 'opp_elo', 'game_num'],
    ['diff', 'color', 'time', 'weekday', 'elo', 'opp_elo', 'game_num'],
    ['diff', 'color', 'game_time', 'weekday', 'elo', 'opp_elo', 'game_num'],
    ['diff', 'time', 'game_time', 'weekday', 'elo', 'opp_elo', 'game_num'],
    ['color', 'time', 'game_time', 'weekday', 'elo', 'opp_elo', 'game_num'],
    ['diff', 'color', 'time', 'game_time', 'weekday', 'elo'],
    ['diff', 'color', 'time', 'game_time', 'weekday', 'opp_elo'],
    ['diff', 'color', 'time', 'game_time', 'weekday', 'game_num'],
    ['diff', 'color', 'time', 'game_time', 'elo', 'opp_elo'],
    ['diff', 'color', 'time', 'game_time', 'elo', 'game_num'],
    ['diff', 'color', 'time', 'game_time', 'opp_elo', 'game_num'],
    ['diff', 'color', 'time', 'weekday', 'elo', 'opp_elo'],
    ['diff', 'color', 'time', 'weekday', 'elo', 'game_num'],
    ['diff', 'color', 'time', 'weekday', 'opp_elo', 'game_num'],
    ['diff', 'color', 'time', 'elo', 'opp_elo', 'game_num'],
    ['diff', 'color', 'game_time', 'weekday', 'elo', 'opp_elo'],
    ['diff', 'color', 'game_time', 'weekday', 'elo', 'game_num'],
    ['diff', 'color', 'game_time', 'weekday', 'opp_elo', 'game_num'],
    ['diff', 'color', 'game_time', 'elo', 'opp_elo', 'game_num'],
    ['diff', 'color', 'weekday', 'elo', 'opp_elo', 'game_num'],
    ['diff', 'time', 'game_time', 'weekday', 'elo', 'opp_elo'],
    ['diff', 'time', 'game_time', 'weekday', 'elo', 'game_num'],
    ['diff', 'time', 'game_time', 'weekday', 'opp_elo', 'game_num'],
    ['diff', 'time', 'game_time', 'elo', 'opp_elo', 'game_num'],
    ['diff', 'time', 'weekday', 'elo', 'opp_elo', 'game_num'],
    ['diff', 'game_time', 'weekday', 'elo', 'opp_elo', 'game_num'],
    ['color', 'time', 'game_time', 'weekday', 'elo', 'opp_elo'],
    ['color', 'time', 'game_time', 'elo', 'opp_elo', 'game_num'],
    ['color', 'time', 'weekday', 'elo', 'opp_elo', 'game_num'],
    ['color', 'game_time', 'weekday', 'elo', 'opp_elo', 'game_num'],
    ['time', 'game_time', 'weekday', 'elo', 'opp_elo', 'game_num'],
    ['diff', 'color', 'time', 'game_time', 'weekday'],
    ['diff', 'color', 'time', 'game_time', 'elo'],
    ['diff', 'color', 'time', 'game_time', 'opp_elo'],
    ['diff', 'color', 'time', 'game_time', 'game_num'],
    ['diff', 'color', 'time', 'weekday', 'elo'],
    ['diff', 'color', 'time', 'weekday', 'opp_elo'],
    ['diff', 'color', 'time', 'weekday', 'game_num'],
    ['diff', 'color', 'time', 'elo', 'opp_elo'],
    ['diff', 'color', 'time', 'elo', 'game_num'],
    ['diff', 'color', 'time', 'opp_elo', 'game_num'],
    ['diff', 'color', 'game_time', 'weekday', 'elo'],
    ['diff', 'color', 'game_time', 'weekday', 'opp_elo'],
    ['diff', 'color', 'game_time', 'weekday', 'game_num'],
    ['diff', 'color', 'game_time', 'elo', 'opp_elo'],
    ['diff', 'color', 'game_time', 'elo', 'game_num'],
    ['diff', 'color', 'game_time', 'opp_elo', 'game_num'],
    ['diff', 'color', 'weekday', 'elo', 'opp_elo'],
    ['diff', 'color', 'weekday', 'elo', 'game_num'],
    ['diff', 'color', 'weekday', 'opp_elo', 'game_num'],
    ['diff', 'color', 'elo', 'opp_elo', 'game_num'],
    ['diff', 'time', 'game_time', 'weekday', 'elo'],
    ['diff', 'time', 'game_time', 'weekday', 'opp_elo'],
    ['diff', 'time', 'game_time', 'weekday', 'game_num'],
    ['diff', 'time', 'game_time', 'elo', 'opp_elo'],
    ['diff', 'time', 'game_time', 'elo', 'game_num'],
    ['diff', 'time', 'game_time', 'opp_elo', 'game_num'],
    ['diff', 'time', 'weekday', 'elo', 'opp_elo'],
    ['diff', 'time', 'weekday', 'elo', 'game_num'],
    ['diff', 'time', 'weekday', 'opp_elo', 'game_num'],
    ['diff', 'time', 'elo', 'opp_elo', 'game_num'],
    ['diff', 'game_time', 'weekday', 'elo', 'opp_elo'],
    ['diff', 'game_time', 'weekday', 'elo', 'game_num'],
    ['diff', 'game_time', 'weekday', 'opp_elo', 'game_num'],
    ['diff', 'game_time', 'elo', 'opp_elo', 'game_num'],
    ['diff', 'weekday', 'elo', 'opp_elo', 'game_num'],
    ['color', 'time', 'game_time', 'elo', 'opp_elo'],
    ['color', 'time', 'weekday', 'elo', 'opp_elo'],
    ['color', 'time', 'elo', 'opp_elo', 'game_num'],
    ['color', 'game_time', 'weekday', 'elo', 'opp_elo'],
    ['color', 'game_time', 'elo', 'opp_elo', 'game_num'],
    ['color', 'weekday', 'elo', 'opp_elo', 'game_num'],
    ['diff', 'color', 'time', 'game_time'], ['diff', 'color', 'time'],
    ['diff', 'color', 'time', 'weekday'], ['diff', 'color', 'time', 'elo'],
    ['diff', 'color', 'time', 'opp_elo'], ['diff', 'color', 'weekday', 'elo'],
    ['diff', 'color', 'time', 'game_num'], ['diff', 'color', 'elo', 'opp_elo'],
    ['diff', 'color', 'game_time', 'weekday'], ['diff', 'color', 'weekday'],
    ['diff', 'color', 'game_time', 'elo'], ['diff', 'time', 'weekday', 'elo'],
    ['diff', 'color', 'game_time', 'opp_elo'], ['diff', 'color', 'game_time'],
    ['diff', 'color', 'game_time', 'game_num'], ['diff', 'color', 'game_num'],
    ['diff', 'color', 'weekday', 'opp_elo'], ['diff', 'time', 'weekday'],
    ['diff', 'color', 'weekday', 'game_num'], ['diff', 'time', 'opp_elo'],
    ['diff', 'color', 'elo', 'game_num'], ['diff', 'time', 'elo', 'opp_elo'],
    ['diff', 'color', 'opp_elo', 'game_num'], ['diff', 'game_time', 'elo'],
    ['diff', 'time', 'game_time', 'weekday'], ['diff', 'weekday', 'elo'],
    ['diff', 'time', 'game_time', 'elo'], ['diff', 'time', 'elo', 'game_num'],
    ['diff', 'time', 'game_time', 'opp_elo'], ['diff', 'color', 'opp_elo'],
    ['diff', 'time', 'game_time', 'game_num'], ['diff', 'time', 'game_num'],
    ['diff', 'time', 'weekday', 'opp_elo'], ['diff', 'game_time', 'weekday'],
    ['diff', 'time', 'weekday', 'game_num'], ['diff', 'time', 'game_time'],
    ['diff', 'time', 'opp_elo', 'game_num'], ['diff', 'game_time', 'opp_elo'],
    ['diff', 'game_time', 'weekday', 'elo'], ['diff', 'weekday', 'opp_elo'],
    ['diff', 'game_time', 'weekday', 'opp_elo'], ['diff', 'elo', 'game_num'],
    ['diff', 'game_time', 'weekday', 'game_num'], ['color', 'elo', 'opp_elo'],
    ['diff', 'game_time', 'elo', 'opp_elo'], ['diff', 'weekday', 'game_num'],
    ['diff', 'game_time', 'elo', 'game_num'], ['diff', 'color', 'elo'],
    ['diff', 'game_time', 'opp_elo', 'game_num'], ['diff', 'time', 'elo'],
    ['diff', 'weekday', 'elo', 'opp_elo'], ['diff', 'game_time', 'game_num'],
    ['diff', 'weekday', 'elo', 'game_num'], ['diff', 'elo', 'opp_elo'],
    ['diff', 'weekday', 'opp_elo', 'game_num'], ['diff', 'color'], ['diff'],
    ['diff', 'elo', 'opp_elo', 'game_num'], ['diff', 'opp_elo', 'game_num'],
    ['color', 'time', 'elo', 'opp_elo'], ['diff', 'game_time'],
    ['color', 'game_time', 'elo', 'opp_elo'], ['diff', 'elo'],
    ['color', 'weekday', 'elo', 'opp_elo'], ['diff', 'opp_elo'],
    ['color', 'elo', 'opp_elo', 'game_num'], ['diff', 'weekday'],
    ['game_time', 'weekday', 'elo', 'opp_elo'], ['diff', 'time'],
    ['game_time', 'elo', 'opp_elo', 'game_num'], ['diff', 'game_num']]

# all_cols = [['diff', 'color', 'time', 'game_time', 'weekday', 'elo',
# 'opp_elo', 'game_num'],
#             ['diff', 'color', 'time', 'game_time',
#                 'weekday', 'elo', 'game_num'],
#             ['diff', 'color', 'time', 'game_time',
#                 'elo', 'opp_elo', 'game_num'],
#             ['diff', 'color', 'game_time', 'weekday',
#                 'elo', 'opp_elo', 'game_num'],
#             ['diff', 'time', 'game_time', 'weekday',
#                 'elo', 'opp_elo', 'game_num'],
#             ['diff', 'color', 'time', 'weekday',
#                 'elo', 'opp_elo', 'game_num'],
#             ['diff', 'color', 'time', 'game_time',
#                 'weekday', 'opp_elo', 'game_num'],
#             ['diff', 'color', 'time',
#                 'game_time', 'weekday', 'elo', 'opp_elo'],
#             ['diff', 'color', 'time', 'game_time', 'weekday',
# 'elo'],
#             ['diff', 'color', 'time', 'game_time', 'elo',
# 'game_num'],
#             ['diff', 'color', 'game_time', 'weekday', 'elo',
# 'game_num'],
#             ['diff', 'time', 'game_time',
#                 'weekday', 'elo', 'game_num'],
#             ['diff', 'color', 'time', 'weekday', 'elo', 'game_num'],
#             ['diff', 'color', 'game_time', 'elo', 'opp_elo', 'game_num'],
#             ['diff', 'time', 'game_time',
#                 'elo', 'opp_elo', 'game_num'],
#             ['diff', 'color', 'time', 'elo', 'opp_elo', 'game_num'],
#             ['diff', 'color', 'weekday', 'elo', 'opp_elo', 'game_num'],
#             ['diff', 'game_time', 'weekday', 'elo', 'opp_elo', 'game_num'],
#             ['time', 'game_time', 'weekday', 'elo', 'opp_elo', 'game_num'],
#             ['diff', 'time', 'weekday', 'elo', 'opp_elo', 'game_num'],
#             ['diff', 'color', 'time',
#                 'game_time', 'opp_elo', 'game_num'],
#             ['diff', 'color', 'game_time', 'weekday', 'opp_elo', 'game_num'],
#             ['diff', 'time', 'game_time',
#                 'weekday', 'opp_elo', 'game_num'],
#             ['diff', 'color', 'time', 'weekday', 'opp_elo', 'game_num'],
#             ['diff', 'color', 'time',
#                 'game_time', 'weekday', 'game_num'],
#             ['diff', 'color', 'time', 'game_time', 'elo', 'opp_elo'],
#             ['diff', 'color', 'game_time', 'weekday', 'elo', 'opp_elo'],
#             ['diff', 'time', 'game_time', 'weekday', 'elo', 'opp_elo'],
#             ['diff', 'color', 'time', 'weekday', 'elo', 'opp_elo'],
#             ['diff', 'color', 'time', 'game_time', 'weekday', 'opp_elo'],
#             ['diff', 'color', 'time', 'game_time', 'elo'],
#             ['diff', 'color', 'game_time', 'weekday', 'elo'],
#             ['diff', 'time', 'game_time', 'weekday', 'elo'],
#             ['diff', 'color', 'time', 'weekday', 'elo'],
#             ['diff', 'color', 'game_time', 'elo', 'game_num'],
#             ['diff', 'time', 'game_time', 'elo', 'game_num'],
#             ['diff', 'color', 'time', 'elo', 'game_num'],
#             ['diff', 'color', 'weekday', 'elo', 'game_num'],
#             ['diff', 'game_time', 'weekday', 'elo', 'game_num'],
#             ['time', 'game_time', 'weekday', 'elo', 'game_num'],
#             ['diff', 'time', 'weekday', 'elo', 'game_num'],
#             ['diff', 'color', 'time', 'game_time', 'game_num'],
#             ['diff', 'color', 'elo', 'opp_elo', 'game_num'],
#             ['diff', 'game_time', 'elo', 'opp_elo', 'game_num'],
#             ['time', 'game_time', 'elo', 'opp_elo', 'game_num'],
#             ['diff', 'time', 'elo', 'opp_elo', 'game_num'],
#             ['diff', 'weekday', 'elo', 'opp_elo', 'game_num'],
#             ['game_time', 'weekday', 'elo', 'opp_elo', 'game_num'],
#             ['time', 'weekday', 'elo', 'opp_elo', 'game_num'],
#             ['diff', 'color', 'game_time', 'opp_elo', 'game_num'],
#             ['diff', 'time', 'game_time', 'opp_elo', 'game_num'],
#             ['diff', 'color', 'time', 'opp_elo', 'game_num'],
#             ['diff', 'color', 'weekday', 'opp_elo', 'game_num'],
#             ['diff', 'game_time', 'weekday', 'opp_elo', 'game_num'],
#             ['time', 'game_time', 'weekday', 'opp_elo', 'game_num'],
#             ['diff', 'time', 'weekday', 'opp_elo', 'game_num'],
#             ['diff', 'color', 'game_time', 'weekday', 'game_num'],
#             ['diff', 'time', 'game_time', 'weekday', 'game_num'],
#             ['diff', 'color', 'time', 'weekday', 'game_num'],
#             ['diff', 'color', 'game_time', 'elo', 'opp_elo'],
#             ['diff', 'time', 'game_time', 'elo', 'opp_elo'],
#             ['diff', 'color', 'time', 'elo', 'opp_elo'],
#             ['diff', 'color', 'weekday', 'elo', 'opp_elo'],
#             ['diff', 'game_time', 'weekday', 'elo', 'opp_elo'],
#             ['time', 'game_time', 'weekday', 'elo', 'opp_elo'],
#             ['diff', 'time', 'weekday', 'elo', 'opp_elo'],
#             ['diff', 'color', 'time', 'game_time', 'opp_elo'],
#             ['diff', 'color', 'game_time', 'weekday', 'opp_elo'],
#             ['diff', 'time', 'game_time', 'weekday', 'opp_elo'],
#             ['diff', 'color', 'time', 'weekday', 'opp_elo'],
#             ['diff', 'color', 'time', 'game_time', 'weekday'],
#             ['diff', 'color', 'game_time', 'elo'],
#             ['diff', 'time', 'game_time', 'elo'],
#             ['diff', 'color', 'time', 'elo'],
#             ['diff', 'color', 'weekday', 'elo'],
#             ['diff', 'game_time', 'weekday', 'elo'],
#             ['time', 'game_time', 'weekday', 'elo'],
#             ['diff', 'time', 'weekday', 'elo'],
#             ['diff', 'color', 'elo', 'game_num'],
#             ['diff', 'game_time', 'elo', 'game_num'],
#             ['time', 'game_time', 'elo', 'game_num'],
#             ['diff', 'time', 'elo', 'game_num'],
#             ['diff', 'weekday', 'elo', 'game_num'],
#             ['game_time', 'weekday', 'elo', 'game_num'],
#             ['time', 'weekday', 'elo', 'game_num'],
#             ['diff', 'color', 'game_time', 'game_num'],
#             ['color', 'time', 'game_time', 'game_num'],
#             ['diff', 'time', 'game_time', 'game_num'],
#             ['diff', 'color', 'opp_elo', 'game_num'],
#             ['diff', 'elo', 'opp_elo', 'game_num'],
#             ['game_time', 'elo', 'opp_elo', 'game_num'],
#             ['time', 'elo', 'opp_elo', 'game_num'],
#             ['weekday', 'elo', 'opp_elo', 'game_num'],
#             ['diff', 'game_time', 'opp_elo', 'game_num'],
#             ['time', 'game_time', 'opp_elo', 'game_num'],
#             ['diff', 'time', 'opp_elo', 'game_num'],
#             ['diff', 'weekday', 'opp_elo', 'game_num'],
#             ['game_time', 'weekday', 'opp_elo', 'game_num'],
#             ['time', 'weekday', 'opp_elo', 'game_num'],
#             ['diff', 'color', 'time', 'game_num'],
#             ['diff', 'color', 'weekday', 'game_num'],
#             ['color', 'game_time', 'weekday', 'game_num'],
#             ['diff', 'game_time', 'weekday', 'game_num'],
#             ['time', 'game_time', 'weekday', 'game_num'],
#             ['diff', 'time', 'weekday', 'game_num'],
#             ['diff', 'color', 'time', 'game_time'],
#             ['diff', 'color', 'elo', 'opp_elo'],
#             ['diff', 'game_time', 'elo', 'opp_elo'],
#             ['time', 'game_time', 'elo', 'opp_elo'],
#             ['diff', 'time', 'elo', 'opp_elo'],
#             ['diff', 'weekday', 'elo', 'opp_elo'],
#             ['game_time', 'weekday', 'elo', 'opp_elo'],
#             ['time', 'weekday', 'elo', 'opp_elo'],
#             ['diff', 'color', 'game_time', 'opp_elo'],
#             ['diff', 'time', 'game_time', 'opp_elo'],
#             ['diff', 'color', 'time', 'opp_elo'],
#             ['diff', 'color', 'weekday', 'opp_elo'],
#             ['diff', 'game_time', 'weekday', 'opp_elo'],
#             ['time', 'game_time', 'weekday', 'opp_elo'],
#             ['diff', 'time', 'weekday', 'opp_elo'],
#             ['diff', 'color', 'game_time', 'weekday'],
#             ['diff', 'time', 'game_time', 'weekday'],
#             ['diff', 'color', 'time'],
#             ['diff', 'color', 'elo'],
#             ['diff', 'game_time', 'elo'],
#             ['time', 'game_time', 'elo'],
#             ['diff', 'time', 'elo'],
#             ['diff', 'weekday', 'elo'],
#             ['game_time', 'weekday', 'elo'],
#             ['time', 'weekday', 'elo'],
#             ['diff', 'color', 'game_num'],
#             ['diff', 'elo', 'game_num'],
#             ['game_time', 'elo', 'game_num'],
#             ['time', 'elo', 'game_num'],
#             ['weekday', 'elo', 'game_num'],
#             ['diff', 'game_time', 'game_num'],
#             ['time', 'game_time', 'game_num'],
#             ['diff', 'opp_elo', 'game_num'],
#             ['elo', 'opp_elo', 'game_num'],
#             ['game_time', 'opp_elo', 'game_num'],
#             ['time', 'opp_elo', 'game_num'],
#             ['weekday', 'opp_elo', 'game_num'],
#             ['diff', 'time', 'game_num'],
#             ['diff', 'weekday', 'game_num'],
#             ['game_time', 'weekday', 'game_num'],
#             ['time', 'weekday', 'game_num'],
#             ['diff', 'color', 'game_time'],
#             ['diff', 'time', 'game_time'],
#             ['diff', 'color', 'opp_elo'],
#             ['diff', 'elo', 'opp_elo'],
#             ['game_time', 'elo', 'opp_elo'],
#             ['time', 'elo', 'opp_elo'],
#             ['weekday', 'elo', 'opp_elo'],
#             ['diff', 'game_time', 'opp_elo'],
#             ['time', 'game_time', 'opp_elo'],
#             ['diff', 'time', 'opp_elo'],
#             ['diff', 'weekday', 'opp_elo'],
#             ['game_time', 'weekday', 'opp_elo'],
#             ['time', 'weekday', 'opp_elo'],
#             ['diff', 'color', 'time'],
#             ['diff', 'color', 'weekday'],
#             ['diff', 'game_time', 'weekday'],
#             ['time', 'game_time', 'weekday'],
#             ['diff', 'time', 'weekday'],
#             ['diff', 'color'],
#             ['diff', 'elo'],
#             ['game_time', 'elo'],
#             ['time', 'elo'],
#             ['weekday', 'elo'],
#             ['diff', 'game_num'],
#             ['elo', 'game_num'],
#             ['opp_elo', 'game_num'],
#             ['diff', 'game_time'],
#             ['diff', 'opp_elo'],
#             ['elo', 'opp_elo'],
#             ['game_time', 'opp_elo'],
#             ['time', 'opp_elo'],
#             ['weekday', 'opp_elo'],
#             ['diff', 'time'],
#             ['diff', 'weekday'],
#             ['diff']]
